services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - ./api_rede_social:/var/www
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy
    entrypoint: /bin/bash -c "composer install && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"

  mysql:
    image: mysql:8.0.33-oracle
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dbredesocial
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    image: node:18.15.0
    container_name: frontend-container
    working_dir: /var/www/frontend_react
    volumes:
      - ./frontend_react:/var/www/frontend_react
    command: >
      /bin/bash -c "
      npm install &&
      npm start
      "
    ports:
      - "3000:3000"
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
